# Generated by Django 5.1.3 on 2024-12-13 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('Numero', models.IntegerField()),
                ('Civilite', models.CharField(max_length=20)),
                ('Nom', models.CharField(max_length=255)),
                ('Prenom', models.CharField(max_length=255)),
                ('Adresse', models.TextField()),
                ('Date_naissance', models.DateField()),
                ('Lieu_naissance', models.CharField(max_length=255)),
                ('Pays', models.CharField(max_length=255)),
                ('Grade', models.CharField(max_length=255)),
                ('Specialite', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filiere_inscription', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Nationalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('nationalite', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('coefficient', models.IntegerField()),
                ('horaire', models.IntegerField()),
                ('Filiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.filiere')),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civilite', models.CharField(choices=[('Monsieur', 'Monsieur'), ('Madame', 'Madame'), ('Mademoiselle', 'Mademoiselle')], max_length=20)),
                ('nom_pre', models.CharField(max_length=255)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('adresse', models.TextField()),
                ('cod_post', models.CharField(max_length=5)),
                ('localite', models.CharField(max_length=255)),
                ('pays', models.CharField(max_length=255)),
                ('plat_form', models.CharField(max_length=255)),
                ('applications', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('filiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.filiere')),
                ('nationalite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.nationalite')),
                ('sports', models.ManyToManyField(blank=True, to='myapp.sport')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FloatField()),
                ('Etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.etudiant')),
                ('Filiere', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='myapp.filiere')),
                ('Module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.module')),
            ],
            options={
                'unique_together': {('Etudiant', 'Module')},
            },
        ),
    ]
