# Generated by Django 5.1.3 on 2024-11-12 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='Module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.module'),
        ),
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.FloatField(),
        ),
    ]
