# Generated by Django 5.1.3 on 2024-11-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
