# Generated by Django 5.1.3 on 2024-11-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_etudiant_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero', models.IntegerField()),
                ('Civilite', models.CharField(max_length=20)),
                ('Nom', models.CharField(max_length=255)),
                ('Prenom', models.CharField(max_length=255)),
                ('Adresse', models.TextField()),
                ('Date_naissance', models.DateField()),
                ('Lieu_naissance', models.CharField(max_length=255)),
                ('Pays', models.CharField(max_length=255)),
                ('Grade', models.CharField(max_length=255)),
                ('Specialite', models.CharField(max_length=255)),
            ],
        ),
    ]
