# Generated by Django 5.1.3 on 2024-12-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_enseignant'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
