# Generated by Django 5.1.3 on 2024-12-12 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_enseignant_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='Filiere',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.filiere'),
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('Etudiant', 'Module')},
        ),
    ]
